/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    pages: Page;
    homepages: Homepage;
    'navigation-menus': NavigationMenu;
    headers: Header;
    footers: Footer;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    homepages: HomepagesSelect<false> | HomepagesSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    headers: HeadersSelect<false> | HeadersSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The tenant this user belongs to. Leave empty for super admins.
   */
  tenant?: (number | null) | Tenant;
  roles: ('admin' | 'editor' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Unique identifier for the tenant (e.g., kallitechnia, ftiaxesite)
   */
  code: string;
  domains?:
    | {
        domain: string;
        status: 'active' | 'disabled';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The tenant this page belongs to. This cannot be changed after creation.
   */
  tenant: number | Tenant;
  title: string;
  /**
   * URL-friendly identifier for this page
   */
  slug: string;
  /**
   * Flexible sections for the page. Page will render even if empty, but will show no content.
   */
  sections?:
    | (
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * Main headline for the hero section (max 120 characters)
             */
            title?: string | null;
            /**
             * Supporting text below the title (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Background image for the hero section. If not provided, a gradient will be used.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Enable call-to-action button
             */
            hasCTA?: boolean | null;
            /**
             * Call-to-action button text (max 50 characters)
             */
            ctaLabel?: string | null;
            /**
             * Call-to-action button URL. Must start with / (internal), http://, or https://
             */
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.hero';
          }
        | {
            /**
             * Welcome section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Welcome paragraphs content using rich text editor. You can add multiple paragraphs in the editor.
             */
            paragraphs?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Welcome section image. If not provided, section will render without image.
             */
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.welcome';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Program items. Grid will be hidden if empty.
             */
            programs?:
              | {
                  /**
                   * Program image. If not provided, item will render without image.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Program title (max 100 characters)
                   */
                  title?: string | null;
                  /**
                   * Program description using rich text editor
                   */
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  /**
                   * Button label (max 50 characters)
                   */
                  buttonLabel?: string | null;
                  /**
                   * Button URL. Must start with / (internal), http://, or https://
                   */
                  buttonUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.programsGrid';
          }
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * Gallery section title
             */
            title?: string | null;
            /**
             * Gallery section subtitle
             */
            subtitle?: string | null;
            /**
             * Show captions below images
             */
            enableCaptions?: boolean | null;
            /**
             * Add images to the gallery. Gallery will be hidden if empty.
             */
            images?:
              | {
                  /**
                   * Gallery image. If not provided, this item will be skipped.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Image title (shown on hover)
                   */
                  title?: string | null;
                  /**
                   * Image description (shown on hover, supports rich text)
                   */
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  /**
                   * Alternative text for accessibility (falls back to title if not provided)
                   */
                  imageAlt?: string | null;
                  /**
                   * Optional caption for the image (max 200 characters)
                   */
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.imageGallery';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Optional "View All" button label (max 50 characters)
             */
            buttonLabel?: string | null;
            /**
             * Optional "View All" button URL. Must start with / (internal), http://, or https://
             */
            buttonUrl?: string | null;
            /**
             * News items. Grid will be hidden if empty. For new implementations, use newsList block instead.
             */
            newsItems?:
              | {
                  /**
                   * News item image. If not provided, item will render without image.
                   */
                  image?: (number | null) | Media;
                  /**
                   * News item date (formatted as text, max 50 characters)
                   */
                  date?: string | null;
                  /**
                   * News item title (max 200 characters)
                   */
                  title?: string | null;
                  /**
                   * News item excerpt (max 300 characters)
                   */
                  excerpt?: string | null;
                  /**
                   * Read more button label (max 50 characters)
                   */
                  readMoreLabel?: string | null;
                  /**
                   * Read more button URL. Must start with / (internal), http://, or https://
                   */
                  readMoreUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.newsGrid';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Number of posts to display per page (1-24)
             */
            itemsPerPage?: number | null;
            /**
             * Show post excerpt in the list
             */
            showExcerpt?: boolean | null;
            /**
             * Show featured image in the list
             */
            showImage?: boolean | null;
            /**
             * Optional "View All" button label (max 50 characters)
             */
            buttonLabel?: string | null;
            /**
             * Optional "View All" button URL. Must start with / (internal), http://, or https://
             */
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.newsList';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Sponsor items. Section will render even if empty.
             */
            sponsors?:
              | {
                  /**
                   * Sponsor logo. If not provided, only name will be displayed.
                   */
                  logo?: (number | null) | Media;
                  /**
                   * Sponsor name (max 100 characters)
                   */
                  name?: string | null;
                  /**
                   * Sponsor website URL. Opens in new tab when clicked. Must start with / (internal), http://, or https://
                   */
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.sponsors';
          }
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * CTA section title (max 100 characters)
             */
            title?: string | null;
            /**
             * CTA section description using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Button text (max 50 characters)
             */
            buttonLabel?: string | null;
            /**
             * Button destination URL. Must start with / (internal), http://, or https://
             */
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.cta';
          }
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * Optional section title
             */
            title?: string | null;
            /**
             * Optional section subtitle
             */
            subtitle?: string | null;
            /**
             * Rich text content using Lexical editor. Start typing to add content.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.richText';
          }
        | {
            /**
             * Quote text (max 500 characters). Block will render nothing if empty.
             */
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.quote';
          }
        | {
            /**
             * Slogan text (max 200 characters). Block will render nothing if empty.
             */
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.slogan';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Text content using rich text editor
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Image position relative to text
             */
            imagePosition?: ('left' | 'right') | null;
            /**
             * Section image. If not provided, section will render without image.
             */
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.imageText';
          }
        | {
            /**
             * Program title (max 120 characters)
             */
            title?: string | null;
            /**
             * Program description using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Image position relative to content
             */
            imagePosition?: ('left' | 'right') | null;
            /**
             * Additional information using rich text editor
             */
            additionalInfo?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Program image. If not provided, section will render without image.
             */
            image?: (number | null) | Media;
            /**
             * Program schedule. Section will render even if empty.
             */
            schedule?:
              | {
                  /**
                   * Day of the week (max 50 characters)
                   */
                  day?: string | null;
                  /**
                   * Time slot (max 50 characters)
                   */
                  time?: string | null;
                  /**
                   * Level (e.g., Beginners, Advanced) (max 50 characters)
                   */
                  level?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Coach name (max 100 characters)
             */
            coachName?: string | null;
            /**
             * Coach photo. If not provided, section will render without photo.
             */
            coachPhoto?: (number | null) | Media;
            /**
             * Coach qualifications/studies (max 200 characters)
             */
            coachStudies?: string | null;
            /**
             * Coach biography using rich text editor
             */
            coachBio?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.programDetail';
          }
        | {
            /**
             * Select a form from the Forms collection. If not selected, form will not be displayed.
             */
            form?: (number | null) | Form;
            /**
             * Optional form title (max 120 characters). Overrides form name if set.
             */
            title?: string | null;
            /**
             * Optional form description using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.form';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Description text above the button using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Button label text (max 100 characters)
             */
            buttonLabel?: string | null;
            /**
             * URL to the file to download. Must start with / (internal), http://, or https://
             */
            fileUrl: string;
            /**
             * Optional file name for download (max 200 characters). If not provided, filename from URL will be used.
             */
            fileName?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.downloadButton';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Contact information items
             */
            items?:
              | {
                  /**
                   * Type of contact information
                   */
                  type: 'address' | 'phone' | 'email' | 'hours';
                  /**
                   * Label for this contact item (e.g., "Διεύθυνση", "Τηλέφωνο")
                   */
                  label?: string | null;
                  /**
                   * Contact information content. Use line breaks for multiple lines.
                   */
                  content?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.contactInfo';
          }
        | {
            /**
             * Optional section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Google Maps embed code (iframe src URL or full iframe HTML). Paste the embed URL from Google Maps.
             */
            embedCode: string;
            /**
             * Map height in pixels (default: 450, min: 200, max: 800)
             */
            height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.googleMap';
          }
        | {
            /**
             * Raw component data. This is a fallback block for unknown component types.
             */
            rawData?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.genericSection';
          }
      )[]
    | null;
  /**
   * Schema version for migration tracking
   */
  schemaVersion?: number | null;
  /**
   * Publication status
   */
  status: 'draft' | 'published';
  /**
   * SEO settings. All fields are optional.
   */
  seo?: {
    /**
     * SEO title (overrides page title if set). Recommended: 50-60 characters.
     */
    title?: string | null;
    /**
     * Meta description for search engines. Recommended: 150-160 characters.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The tenant this media belongs to. Automatically set based on your user account when creating. Admins can manually select a different tenant.
   */
  tenant: number | Tenant;
  /**
   * Alternative text for the image (required for accessibility, max 200 characters)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * The tenant this form belongs to
   */
  tenant: number | Tenant;
  /**
   * Internal name for this form
   */
  name: string;
  /**
   * URL-friendly identifier for this form
   */
  slug: string;
  /**
   * Form fields configuration
   */
  fields: {
    /**
     * Field type
     */
    type: 'text' | 'email' | 'tel' | 'textarea' | 'number' | 'select' | 'checkbox';
    /**
     * Field label shown to users
     */
    label: string;
    /**
     * Field name (used in form submission)
     */
    name: string;
    /**
     * Is this field required?
     */
    required?: boolean | null;
    /**
     * Placeholder text
     */
    placeholder?: string | null;
    /**
     * Options for select field
     */
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Message shown after successful submission
   */
  successMessage?: string | null;
  /**
   * Optional URL to redirect after submission (must be http/https or internal /)
   */
  redirectUrl?: string | null;
  /**
   * Form status
   */
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepages".
 */
export interface Homepage {
  id: number;
  /**
   * Each tenant can have exactly one homepage. This cannot be changed after creation.
   */
  tenant: number | Tenant;
  /**
   * Flexible sections for the homepage. Consider starting with a hero block for best UX.
   */
  sections?:
    | (
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * Main headline for the hero section (max 120 characters)
             */
            title?: string | null;
            /**
             * Supporting text below the title (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Background image for the hero section. If not provided, a gradient will be used.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Enable call-to-action button
             */
            hasCTA?: boolean | null;
            /**
             * Call-to-action button text (max 50 characters)
             */
            ctaLabel?: string | null;
            /**
             * Call-to-action button URL. Must start with / (internal), http://, or https://
             */
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.hero';
          }
        | {
            /**
             * Welcome section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Welcome paragraphs content using rich text editor. You can add multiple paragraphs in the editor.
             */
            paragraphs?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Welcome section image. If not provided, section will render without image.
             */
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.welcome';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Program items. Grid will be hidden if empty.
             */
            programs?:
              | {
                  /**
                   * Program image. If not provided, item will render without image.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Program title (max 100 characters)
                   */
                  title?: string | null;
                  /**
                   * Program description using rich text editor
                   */
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  /**
                   * Button label (max 50 characters)
                   */
                  buttonLabel?: string | null;
                  /**
                   * Button URL. Must start with / (internal), http://, or https://
                   */
                  buttonUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.programsGrid';
          }
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * Gallery section title
             */
            title?: string | null;
            /**
             * Gallery section subtitle
             */
            subtitle?: string | null;
            /**
             * Show captions below images
             */
            enableCaptions?: boolean | null;
            /**
             * Add images to the gallery. Gallery will be hidden if empty.
             */
            images?:
              | {
                  /**
                   * Gallery image. If not provided, this item will be skipped.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Image title (shown on hover)
                   */
                  title?: string | null;
                  /**
                   * Image description (shown on hover, supports rich text)
                   */
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  /**
                   * Alternative text for accessibility (falls back to title if not provided)
                   */
                  imageAlt?: string | null;
                  /**
                   * Optional caption for the image (max 200 characters)
                   */
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.imageGallery';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Optional "View All" button label (max 50 characters)
             */
            buttonLabel?: string | null;
            /**
             * Optional "View All" button URL. Must start with / (internal), http://, or https://
             */
            buttonUrl?: string | null;
            /**
             * News items. Grid will be hidden if empty. For new implementations, use newsList block instead.
             */
            newsItems?:
              | {
                  /**
                   * News item image. If not provided, item will render without image.
                   */
                  image?: (number | null) | Media;
                  /**
                   * News item date (formatted as text, max 50 characters)
                   */
                  date?: string | null;
                  /**
                   * News item title (max 200 characters)
                   */
                  title?: string | null;
                  /**
                   * News item excerpt (max 300 characters)
                   */
                  excerpt?: string | null;
                  /**
                   * Read more button label (max 50 characters)
                   */
                  readMoreLabel?: string | null;
                  /**
                   * Read more button URL. Must start with / (internal), http://, or https://
                   */
                  readMoreUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.newsGrid';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Number of posts to display per page (1-24)
             */
            itemsPerPage?: number | null;
            /**
             * Show post excerpt in the list
             */
            showExcerpt?: boolean | null;
            /**
             * Show featured image in the list
             */
            showImage?: boolean | null;
            /**
             * Optional "View All" button label (max 50 characters)
             */
            buttonLabel?: string | null;
            /**
             * Optional "View All" button URL. Must start with / (internal), http://, or https://
             */
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.newsList';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Section subtitle (max 240 characters)
             */
            subtitle?: string | null;
            /**
             * Sponsor items. Section will render even if empty.
             */
            sponsors?:
              | {
                  /**
                   * Sponsor logo. If not provided, only name will be displayed.
                   */
                  logo?: (number | null) | Media;
                  /**
                   * Sponsor name (max 100 characters)
                   */
                  name?: string | null;
                  /**
                   * Sponsor website URL. Opens in new tab when clicked. Must start with / (internal), http://, or https://
                   */
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.sponsors';
          }
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * CTA section title (max 100 characters)
             */
            title?: string | null;
            /**
             * CTA section description using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Button text (max 50 characters)
             */
            buttonLabel?: string | null;
            /**
             * Button destination URL. Must start with / (internal), http://, or https://
             */
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.cta';
          }
        | {
            __deprecated?: boolean | null;
            schemaVersion?: number | null;
            /**
             * Optional section title
             */
            title?: string | null;
            /**
             * Optional section subtitle
             */
            subtitle?: string | null;
            /**
             * Rich text content using Lexical editor. Start typing to add content.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.richText';
          }
        | {
            /**
             * Quote text (max 500 characters). Block will render nothing if empty.
             */
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.quote';
          }
        | {
            /**
             * Slogan text (max 200 characters). Block will render nothing if empty.
             */
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.slogan';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Text content using rich text editor
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Image position relative to text
             */
            imagePosition?: ('left' | 'right') | null;
            /**
             * Section image. If not provided, section will render without image.
             */
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.imageText';
          }
        | {
            /**
             * Program title (max 120 characters)
             */
            title?: string | null;
            /**
             * Program description using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Image position relative to content
             */
            imagePosition?: ('left' | 'right') | null;
            /**
             * Additional information using rich text editor
             */
            additionalInfo?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Program image. If not provided, section will render without image.
             */
            image?: (number | null) | Media;
            /**
             * Program schedule. Section will render even if empty.
             */
            schedule?:
              | {
                  /**
                   * Day of the week (max 50 characters)
                   */
                  day?: string | null;
                  /**
                   * Time slot (max 50 characters)
                   */
                  time?: string | null;
                  /**
                   * Level (e.g., Beginners, Advanced) (max 50 characters)
                   */
                  level?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Coach name (max 100 characters)
             */
            coachName?: string | null;
            /**
             * Coach photo. If not provided, section will render without photo.
             */
            coachPhoto?: (number | null) | Media;
            /**
             * Coach qualifications/studies (max 200 characters)
             */
            coachStudies?: string | null;
            /**
             * Coach biography using rich text editor
             */
            coachBio?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.programDetail';
          }
        | {
            /**
             * Select a form from the Forms collection. If not selected, form will not be displayed.
             */
            form?: (number | null) | Form;
            /**
             * Optional form title (max 120 characters). Overrides form name if set.
             */
            title?: string | null;
            /**
             * Optional form description using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.form';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Description text above the button using rich text editor
             */
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Button label text (max 100 characters)
             */
            buttonLabel?: string | null;
            /**
             * URL to the file to download. Must start with / (internal), http://, or https://
             */
            fileUrl: string;
            /**
             * Optional file name for download (max 200 characters). If not provided, filename from URL will be used.
             */
            fileName?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.downloadButton';
          }
        | {
            /**
             * Section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Contact information items
             */
            items?:
              | {
                  /**
                   * Type of contact information
                   */
                  type: 'address' | 'phone' | 'email' | 'hours';
                  /**
                   * Label for this contact item (e.g., "Διεύθυνση", "Τηλέφωνο")
                   */
                  label?: string | null;
                  /**
                   * Contact information content. Use line breaks for multiple lines.
                   */
                  content?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.contactInfo';
          }
        | {
            /**
             * Optional section title (max 120 characters)
             */
            title?: string | null;
            /**
             * Google Maps embed code (iframe src URL or full iframe HTML). Paste the embed URL from Google Maps.
             */
            embedCode: string;
            /**
             * Map height in pixels (default: 450, min: 200, max: 800)
             */
            height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.googleMap';
          }
        | {
            /**
             * Raw component data. This is a fallback block for unknown component types.
             */
            rawData?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kallitechnia.genericSection';
          }
      )[]
    | null;
  /**
   * Schema version for migration tracking
   */
  schemaVersion?: number | null;
  /**
   * Publication status
   */
  status: 'draft' | 'published';
  /**
   * SEO settings. All fields are optional.
   */
  seo?: {
    /**
     * SEO title for the homepage. Recommended: 50-60 characters.
     */
    title?: string | null;
    /**
     * Meta description for search engines. Recommended: 150-160 characters.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  /**
   * The tenant this navigation menu belongs to. This cannot be changed after creation.
   */
  tenant: number | Tenant;
  /**
   * Internal name for this navigation menu
   */
  title: string;
  /**
   * Navigation menu items. Menu will be empty if no items are added.
   */
  items?:
    | {
        /**
         * Menu item label (max 50 characters)
         */
        label: string;
        /**
         * Link type: Internal links to a page, External links to a URL
         */
        type: 'internal' | 'external';
        /**
         * Select a page for internal links
         */
        page?: (number | null) | Page;
        /**
         * External URL. Must start with / (internal), http://, or https://
         */
        url?: string | null;
        /**
         * Open link in a new tab
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers".
 */
export interface Header {
  id: number;
  /**
   * Each tenant can have exactly one header. This cannot be changed after creation.
   */
  tenant: number | Tenant;
  /**
   * Logo image for the header
   */
  logo?: (number | null) | Media;
  /**
   * Navigation menu to display in the header
   */
  navigationMenu?: (number | null) | NavigationMenu;
  /**
   * Show a top bar above the main header
   */
  enableTopBar?: boolean | null;
  /**
   * Text to display in the top bar (max 100 characters)
   */
  topBarText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: number;
  /**
   * Each tenant can have exactly one footer. This cannot be changed after creation.
   */
  tenant: number | Tenant;
  /**
   * Copyright text to display in the footer (max 200 characters)
   */
  copyrightText?: string | null;
  /**
   * Social media links. Footer will render even if empty.
   */
  socialLinks?:
    | {
        /**
         * Social media platform (e.g., Facebook, Twitter, Instagram)
         */
        platform: string;
        /**
         * URL to the social media profile. Must start with http:// or https://
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  /**
   * The form this submission belongs to
   */
  form: number | Form;
  /**
   * Form submission data
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?: {
    /**
     * IP address of submitter
     */
    ip?: string | null;
    /**
     * User agent string
     */
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The tenant this post belongs to. This cannot be changed after creation.
   */
  tenant: number | Tenant;
  /**
   * Post title (required, max 200 characters)
   */
  title: string;
  /**
   * URL-friendly identifier for this post. Must be unique.
   */
  slug: string;
  /**
   * Short excerpt for previews (max 300 characters)
   */
  excerpt?: string | null;
  /**
   * Post content using Lexical editor
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Featured image for the post. Used in listings and previews.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Publication date. Used for sorting and display.
   */
  publishedAt?: string | null;
  /**
   * Publication status. Drafts are hidden from frontend.
   */
  status: 'draft' | 'published';
  /**
   * SEO settings. All fields are optional.
   */
  seo?: {
    /**
     * SEO title (overrides post title if set). Recommended: 50-60 characters.
     */
    title?: string | null;
    /**
     * Meta description for search engines. Recommended: 150-160 characters.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'homepages';
        value: number | Homepage;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'headers';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footers';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenant?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  domains?:
    | T
    | {
        domain?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        'kallitechnia.hero'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              hasCTA?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.welcome'?:
          | T
          | {
              title?: T;
              paragraphs?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.programsGrid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              programs?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    buttonLabel?: T;
                    buttonUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.imageGallery'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              subtitle?: T;
              enableCaptions?: T;
              images?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    imageAlt?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.newsGrid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              newsItems?:
                | T
                | {
                    image?: T;
                    date?: T;
                    title?: T;
                    excerpt?: T;
                    readMoreLabel?: T;
                    readMoreUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.newsList'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              itemsPerPage?: T;
              showExcerpt?: T;
              showImage?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.sponsors'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              sponsors?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.cta'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.richText'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              subtitle?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.quote'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.slogan'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.imageText'?:
          | T
          | {
              title?: T;
              content?: T;
              imagePosition?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.programDetail'?:
          | T
          | {
              title?: T;
              description?: T;
              imagePosition?: T;
              additionalInfo?: T;
              image?: T;
              schedule?:
                | T
                | {
                    day?: T;
                    time?: T;
                    level?: T;
                    id?: T;
                  };
              coachName?: T;
              coachPhoto?: T;
              coachStudies?: T;
              coachBio?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.form'?:
          | T
          | {
              form?: T;
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.downloadButton'?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              fileUrl?: T;
              fileName?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.contactInfo'?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    type?: T;
                    label?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.googleMap'?:
          | T
          | {
              title?: T;
              embedCode?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.genericSection'?:
          | T
          | {
              rawData?: T;
              id?: T;
              blockName?: T;
            };
      };
  schemaVersion?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepages_select".
 */
export interface HomepagesSelect<T extends boolean = true> {
  tenant?: T;
  sections?:
    | T
    | {
        'kallitechnia.hero'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              hasCTA?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.welcome'?:
          | T
          | {
              title?: T;
              paragraphs?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.programsGrid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              programs?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    buttonLabel?: T;
                    buttonUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.imageGallery'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              subtitle?: T;
              enableCaptions?: T;
              images?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    imageAlt?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.newsGrid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              newsItems?:
                | T
                | {
                    image?: T;
                    date?: T;
                    title?: T;
                    excerpt?: T;
                    readMoreLabel?: T;
                    readMoreUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.newsList'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              itemsPerPage?: T;
              showExcerpt?: T;
              showImage?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.sponsors'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              sponsors?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.cta'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.richText'?:
          | T
          | {
              __deprecated?: T;
              schemaVersion?: T;
              title?: T;
              subtitle?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.quote'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.slogan'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.imageText'?:
          | T
          | {
              title?: T;
              content?: T;
              imagePosition?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.programDetail'?:
          | T
          | {
              title?: T;
              description?: T;
              imagePosition?: T;
              additionalInfo?: T;
              image?: T;
              schedule?:
                | T
                | {
                    day?: T;
                    time?: T;
                    level?: T;
                    id?: T;
                  };
              coachName?: T;
              coachPhoto?: T;
              coachStudies?: T;
              coachBio?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.form'?:
          | T
          | {
              form?: T;
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.downloadButton'?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              fileUrl?: T;
              fileName?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.contactInfo'?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    type?: T;
                    label?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'kallitechnia.googleMap'?:
          | T
          | {
              title?: T;
              embedCode?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        'kallitechnia.genericSection'?:
          | T
          | {
              rawData?: T;
              id?: T;
              blockName?: T;
            };
      };
  schemaVersion?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers_select".
 */
export interface HeadersSelect<T extends boolean = true> {
  tenant?: T;
  logo?: T;
  navigationMenu?: T;
  enableTopBar?: T;
  topBarText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  tenant?: T;
  copyrightText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  fields?:
    | T
    | {
        type?: T;
        label?: T;
        name?: T;
        required?: T;
        placeholder?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  successMessage?: T;
  redirectUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  payload?: T;
  metadata?:
    | T
    | {
        ip?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}